package Util;

public enum Action {
    HOME,
    ADD_CLIENT,
    EDIT_CLIENT,
    DELETE_CLIENT,
    SEARCH_CLIENT,
    VIEW_CLIENTS,
    ADD_ENTRY,
    VIEW_NUMBER_OF_ENTRIES_FOR_A_CLIENT,
    VIEW_REWARDS
}
